### ISSUE TITLE
Consul ESM has dissociative identity disorder?

### ISSUE THREAD

**Issue by ashald** [hashicorp/consul-esm#39]
We runs Consul ESM in 3-node "clusters" in several Consul clusters.

TL;DR this is what we see:

## Sample 1

![image](https://user-images.githubusercontent.com/397987/57542061-8f2fd300-731e-11e9-9751-4ec1ac78dc5d.png)

Here is how the KV looks like in YAML-like representation:
```yaml
KV:
  __esm__:
      leader: "" # part of session '3034f8c2-ddd3-a733-c3a4-a07b173b0ab7' held by host ''***31'
      agents:
        consul-esm:5460c1fa-4368-62c3-311a-0934fa005cdc: {"Nodes":null,"Probes":["esm-test-host-192-10","esm-test-host-192-15","esm-test-host-192-20"]} # entry name corresponds to ESM running on ***33, part of session '3034f8c2-ddd3-a733-c3a4-a07b173b0ab7' owned by host ''***31'
        consul-esm:6b66d99a-f83b-d678-b710-42b5242347af: {"Nodes":null,"Probes":["esm-test-host-192-11","esm-test-host-192-16","esm-test-host-192-21"]} # entry name corresponds to ESM running on ***33, part of session '3034f8c2-ddd3-a733-c3a4-a07b173b0ab7' owned by host ''***31'
        consul-esm:ab78b0e1-5bb7-6114-d758-5a59dc814361: {"Nodes":null,"Probes":["esm-test-host-192-12","esm-test-host-192-17","esm-test-host-192-22"]} # entry name corresponds to ESM running on ***31, part of session '3034f8c2-ddd3-a733-c3a4-a07b173b0ab7' owned by host ''***31'
        consul-esm:ec9c23a5-b092-295b-76d6-dc7f0508da69: {"Nodes":null,"Probes":["esm-test-host-192-13","esm-test-host-192-18","esm-test-host-192-23"]} # entry name corresponds to ESM running on ***32, part of session '3034f8c2-ddd3-a733-c3a4-a07b173b0ab7' owned by host ''***31'
        consul-esm:f2001c4c-07ce-7a91-bcf3-67c168c9236d: {"Nodes":null,"Probes":["esm-test-host-192-14","esm-test-host-192-19"]}                        # entry name corresponds to ESM running on ***32, part of session '3034f8c2-ddd3-a733-c3a4-a07b173b0ab7' owned by host ''***31'
      probes:
        esm-test-host-192-10: AQAAAA7UZ58zIPqZFf//
        esm-test-host-192-12: AQAAAA7UZ580Dz4bBf//
        esm-test-host-192-14: AQAAAA7UZ58tMd74BP//
        esm-test-host-192-15: AQAAAA7UZ58vMuHD9///
        esm-test-host-192-17: AQAAAA7UZ58tJvKprv//
        esm-test-host-192-19: AQAAAA7UZ58yLAwK2f//
        esm-test-host-192-20: AQAAAA7UZ58pCS3VxP//
        esm-test-host-192-22: AQAAAA7UZ58xCQc+a///
        

```
Node status:
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/397987/57543750-3c0c4f00-7323-11e9-8deb-e6d0ca9bffd8.png">

## Sample 2

<img width="1616" alt="image" src="https://user-images.githubusercontent.com/397987/57542007-67d90600-731e-11e9-8838-014911969e0d.png">

Here is how the KV looks like in YAML-like representation:

```yaml
KV:
  __esm__:
      leader: "" # part of session 'edc63fda-a348-f7a2-bdd5-749cf57751f1' held by host ''***11'
      agents:
        consul-esm:556c6406-b7fe-199f-716c-6593e2512d46: {"Nodes":null,"Probes":["esm-test-host-190-10","esm-test-host-190-14","esm-test-host-190-18"]} # entry name corresponds to ESM running on ***12
        consul-esm:a73bd45f-8ddd-26e1-2e0d-9ffa62306be5: {"Nodes":null,"Probes":["esm-test-host-190-11","esm-test-host-190-15","esm-test-host-190-19"]} # entry name corresponds to ESM running on ***21
        consul-esm:bedfcb00-5198-4e4c-b644-9c6df993a222: {"Nodes":null,"Probes":["esm-test-host-190-12","esm-test-host-190-16","esm-test-host-190-20"]} # entry name corresponds to ESM running on ***11
        consul-esm:d1da7756-897e-c35b-7bb1-a9bd8cd34705: {"Nodes":null,"Probes":["esm-test-host-190-13","esm-test-host-190-17","esm-test-host-190-21"]} # entry name corresponds to ESM running on ***11
```

When we just registered external services, a week or few ago, 3 oof them that correspond to:
```yaml
consul-esm:d1da7756-897e-c35b-7bb1-a9bd8cd34705: {"Nodes":null,"Probes":["esm-test-host-190-13","esm-test-host-190-17","esm-test-host-190-21"]} # entry name corresponds to ESM running on ***11
```
we're missing info about the status but after a while became "green":
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/397987/57543550-ae306400-7322-11e9-9406-e7d2424f6a73.png">

# Conclusion
Not really sure what it all means but my gut feeling is that it's not normal. We would be looking forward to getting this addressed and would appeciate an advice on how we can get it to a "normal state". Thanks!
